// 普通素材
export const QUERY_MATERIAL_LIST = 'QUERY_MATERIAL_LIST' //查询普通素材
export const METERIAL_ADD_TEXT = 'METERIAL_ADD_TEXT' // 添加素材文本
export const METERIAL_UPLOAD = 'METERIAL_UPLOAD' // 上传素材
export const QUERY_MATERIAL_LIST_MINIAPP = 'QUERY_MATERIAL_LIST_MINIAPP' // 查询小程序素材
export const QUERY_MATERIAL_LIST_IMAGE = 'QUERY_MATERIAL_LIST_IMAGE' // 查询图片素材
